import { createContext, useContext, useMemo, useState } from 'react'

const LANG_KEY = 'sevasetu_language'

const translations = {
  en: {
    language: 'Language',
    english: 'English',
    hindi: 'Hindi',
    hinglish: 'Hinglish',
    status: 'Status',
    online: 'Online',
    offline: 'Offline',
    logout: 'Logout',
    refresh: 'Refresh',
    patient: 'Patient',
    nurse: 'Nurse',
    bookNurse: 'Book a Nurse',
    bookSubtitle: "Describe your need and we'll find the right nurse",
    describeProblem: 'Describe your problem',
    requirements: 'Specific requirements',
    serviceType: 'Service Type',
    temporary: 'Temporary',
    longterm: 'Long-term',
    pickupLocation: 'Pickup location',
    useCurrentLocation: 'Use current location',
    address: 'Your Address',
    submitRequest: 'Submit Request',
    submitting: 'Submitting...',
    myRequests: 'My Requests',
    activeVisits: 'Active Visits',
    inProgress: 'In Progress',
    todayEarnings: 'Today Earnings',
    openRequests: 'Open Requests',
    assignedRequests: 'Assigned Requests',
    updateLocation: 'Update location',
    acceptRequest: 'Accept Request',
    acceptInterview: 'Accept & Schedule Interview',
    emergencySos: 'Emergency SOS',
    checkInOtp: 'Visit Check-in OTP',
    checkOutOtp: 'Visit Check-out OTP',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    patientReport: 'Patient behavior report',
    submitReport: 'Submit report',
    noOpenRequests: 'No open patient requests right now',
    noAssignedRequests: 'No assigned requests yet',
    noRequests: 'No requests yet. Book a nurse above to get started.',
    aiAssistant: 'AI Health Assistant',
    nextPending: 'We are finding a matching nurse.',
    nextSafety: 'A nurse will be assigned after admin safety review.',
    nextInterview: 'Long-term nurse AI interview is scheduled.',
    nextMatched: 'Nurse is on the way. Share check-in OTP after arrival.',
    nextInProgress: 'Visit is in progress. Share check-out OTP after work is complete.',
    nextCompleted: 'Visit is complete. Please rate the nurse.',
    nextCompletedRated: 'Visit is complete.',
    nextCancelled: 'Request has been cancelled.',
  },
  hi: {
    language: 'भाषा',
    english: 'अंग्रेजी',
    hindi: 'हिंदी',
    hinglish: 'हिंग्लिश',
    status: 'स्थिति',
    online: 'ऑनलाइन',
    offline: 'ऑफलाइन',
    logout: 'लॉगआउट',
    refresh: 'रीफ्रेश',
    patient: 'मरीज',
    nurse: 'नर्स',
    bookNurse: 'नर्स बुक करें',
    bookSubtitle: 'अपनी जरूरत बताएं, हम सही नर्स ढूंढेंगे',
    describeProblem: 'अपनी समस्या बताएं',
    requirements: 'खास जरूरतें',
    serviceType: 'सेवा प्रकार',
    temporary: 'अस्थायी',
    longterm: 'लंबी अवधि',
    pickupLocation: 'पिकअप लोकेशन',
    useCurrentLocation: 'वर्तमान लोकेशन इस्तेमाल करें',
    address: 'आपका पता',
    submitRequest: 'रिक्वेस्ट भेजें',
    submitting: 'भेज रहे हैं...',
    myRequests: 'मेरी रिक्वेस्ट',
    activeVisits: 'एक्टिव विजिट',
    inProgress: 'चल रही हैं',
    todayEarnings: 'आज की कमाई',
    openRequests: 'ओपन रिक्वेस्ट',
    assignedRequests: 'असाइन रिक्वेस्ट',
    updateLocation: 'लोकेशन अपडेट करें',
    acceptRequest: 'रिक्वेस्ट स्वीकार करें',
    acceptInterview: 'स्वीकार करें और इंटरव्यू शेड्यूल करें',
    emergencySos: 'इमरजेंसी SOS',
    checkInOtp: 'विजिट चेक-इन OTP',
    checkOutOtp: 'विजिट चेक-आउट OTP',
    checkIn: 'चेक-इन',
    checkOut: 'चेक-आउट',
    patientReport: 'मरीज व्यवहार रिपोर्ट',
    submitReport: 'रिपोर्ट भेजें',
    noOpenRequests: 'अभी कोई ओपन मरीज रिक्वेस्ट नहीं है',
    noAssignedRequests: 'अभी कोई असाइन रिक्वेस्ट नहीं है',
    noRequests: 'अभी कोई रिक्वेस्ट नहीं है। ऊपर से नर्स बुक करें।',
    aiAssistant: 'AI हेल्थ असिस्टेंट',
    nextPending: 'हम मैचिंग नर्स ढूंढ रहे हैं।',
    nextSafety: 'एडमिन सेफ्टी रिव्यू के बाद नर्स असाइन होगी।',
    nextInterview: 'लंबी अवधि की नर्स का AI इंटरव्यू शेड्यूल है।',
    nextMatched: 'नर्स रास्ते में है। पहुंचने पर चेक-इन OTP शेयर करें।',
    nextInProgress: 'विजिट चल रही है। काम पूरा होने पर चेक-आउट OTP शेयर करें।',
    nextCompleted: 'विजिट पूरी हो गई है। कृपया नर्स को रेटिंग दें।',
    nextCompletedRated: 'विजिट पूरी हो गई है।',
    nextCancelled: 'रिक्वेस्ट कैंसल हो गई है।',
  },
  hinglish: {
    language: 'Language',
    english: 'English',
    hindi: 'Hindi',
    hinglish: 'Hinglish',
    status: 'Status',
    online: 'Online',
    offline: 'Offline',
    logout: 'Logout',
    refresh: 'Refresh',
    patient: 'Patient',
    nurse: 'Nurse',
    bookNurse: 'Nurse Book Karein',
    bookSubtitle: 'Apni need batayein, hum right nurse find karenge',
    describeProblem: 'Apni problem batayein',
    requirements: 'Specific requirements',
    serviceType: 'Service Type',
    temporary: 'Temporary',
    longterm: 'Long-term',
    pickupLocation: 'Pickup location',
    useCurrentLocation: 'Current location use karein',
    address: 'Aapka Address',
    submitRequest: 'Request Submit Karein',
    submitting: 'Submit ho raha hai...',
    myRequests: 'Meri Requests',
    activeVisits: 'Active Visits',
    inProgress: 'In Progress',
    todayEarnings: 'Aaj ki Earnings',
    openRequests: 'Open Requests',
    assignedRequests: 'Assigned Requests',
    updateLocation: 'Location update karein',
    acceptRequest: 'Request Accept Karein',
    acceptInterview: 'Accept & Interview Schedule',
    emergencySos: 'Emergency SOS',
    checkInOtp: 'Visit Check-in OTP',
    checkOutOtp: 'Visit Check-out OTP',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    patientReport: 'Patient behavior report',
    submitReport: 'Report Submit',
    noOpenRequests: 'Abhi koi open patient request nahi hai',
    noAssignedRequests: 'Abhi koi assigned request nahi hai',
    noRequests: 'Abhi koi request nahi hai. Upar se nurse book karein.',
    aiAssistant: 'AI Health Assistant',
    nextPending: 'Hum matching nurse dhoond rahe hain.',
    nextSafety: 'Admin safety review ke baad nurse assign hogi.',
    nextInterview: 'Long-term nurse ka AI interview scheduled hai.',
    nextMatched: 'Nurse aa rahi hai. Pahunchne par check-in OTP share karein.',
    nextInProgress: 'Visit chal rahi hai. Kaam complete hone par check-out OTP share karein.',
    nextCompleted: 'Visit complete ho gayi hai. Nurse ko rating dein.',
    nextCompletedRated: 'Visit complete ho gayi hai.',
    nextCancelled: 'Request cancel ho gayi hai.',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem(LANG_KEY) || 'en')

  const setLanguage = (nextLanguage) => {
    setLanguageState(nextLanguage)
    localStorage.setItem(LANG_KEY, nextLanguage)
  }

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (key) => translations[language]?.[key] || translations.en[key] || key,
  }), [language])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider')
  return context
}
